apiVersion: v1
kind: Service
metadata:
  name: webapp
spec:
  ports:
  - port: 3000
  type: LoadBalancer
  selector:
    app: webapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: webapp:v1
        ports:
        - containerPort: 3000
