apiVersion: skaffold/v4beta7
kind: Config

portForward:
  - resourceType: Deployment
    resourceName: webapp
    port: 3000

build:
  artifacts:
  - image: webapp
    context: ./backend
    sync:
      manual:
      - src: 'src/data/**/*.html'
        dest: .

manifests:
  rawYaml:
    - ./k8s/deployment.yaml

deploy:
  kubectl: {}